config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  resource :feedback, only: %i(new create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < MailForm::Base
  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :email, validate: EMAIL_REGEX
  attribute :message
  attribute :name, validate: true

  def headers
    {
      subject: "New feedback",
      to: ENV.fetch("FEEDBACK_EMAIL"),
      from: email
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  respond_to :html
  responders :flash
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  expose :feedback

  def new
  end

  def create
    feedback.deliver

    respond_with feedback, location: root_path
  end

  private

  def feedback_params
    params.fetch(:feedback, {}).permit(:email, :name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_messages.html.slim
- bulma_types = { "notice" => "is-info", "alert" => "is-danger" }

- flash.each do |type, content|
  .notification class="#{bulma_types[type]}"
    = content
    button.notification-close.delete

app/views/dashboard/index.html.slim
.card.is-half.column.is-offset-one-quarter
  header.card-header
    p.card-header-title Wisdom of the day
  .card-content
    .content The best code I have ever written is the code I never wrote
    .content
      = link_to "Leave feedback about this amazing webpage", new_feedback_path

app/views/feedbacks/new.html.slim
.columns
  .column.is-offset-4
    .columns
      .column.has-text-left
        h3.title.is-3 Stay in touch

    .columns
      .column.is-half
        = simple_form_for feedback, url: feedback_path, wrapper: :bulma do |f|
          = f.input :name
          = f.input :email
          = f.input :message, as: :text

          = f.button :submit, "Submit", class: "is-medium is-primary"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title FsRailsPractice
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  body
    .columns
      .column.is-6.is-offset-3
        = render "messages"
    = yield